title: Joan Iavintsoa R. # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  From Political Science formation to Economics, I am currently passionated about datas for them being a powerful orientating driving decision.   
  <br><br>
  Environmental (especially in energy domain)  datas permit us to understand the ecological consequences of our impacts. My goal is to use my data manipulation skills to 
  raise awareness about these issues and orient decisions makers with full insights and further actions to minimize/reduce our impacts.  
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
